# サイトの基本設定
title: ""
# description: "パズルやトリビアクイズをまとめているサイトです"
# baseurl: ""  # リポジトリ名がユーザー名.github.ioの場合は空欄
# url: ""      # 本番環境のURLを設定

# # ビルド設定
markdown: kramdown
# kramdown:
#   math_engine: mathjax

# # ファイル除外設定
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor

# # デフォルトのFront Matter設定
# defaults:
#   -
#     scope:
#       path: ""      # 空文字は全てのファイルを意味する
#       type: "pages" # pagesはmarkdownやhtmlファイルを指す
#     values:
#       layout: "default"  # デフォルトレイアウトの指定
#       mathjax: false     # デフォルトでMathJaxは無効